fix: pin subgraph versions
With a fresh install, I was encountering this error.

    Error: require() of ES Module packages/subgraph/node_modules/onetime/index.js from
       packages/subgraph/node_modules/restore-cursor/index.js not supported.
       Instead change the require of packages/subgraph/node_modules/onetime/index.js in
       packages/subgraph/node_modules/restore-cursor/index.js to a dynamic import() which is
       available in all CommonJS modules.
       Code: ERR_REQUIRE_ESM

After pinning, the error went away.